export const constant = {
  es: {
    title: 'De la idea a la acción',
    description: 'en 3 simples pasos',
    subtitle: 'Tus clientes quieren respuestas rápidas, claras y al momento.',
    subtitleBold: 'Con OrishIA, eso se convierte en tu valor diferencia.',
    firstTitle: 'ANÁLISIS Y DIAGNÓSTICO',
    firstDescription: 'IDENTIFICAMOS TUS NECESIDADES ESPECÍFICAS',
    firstStep: 'Paso 1.',
    secondTitle: 'CONFIGURACIÓN PERSONALIZADA',
    secondDescription: 'DISEÑAMOS UNA SOLUCIÓN HECHA A MEDIDA',
    secondStep: 'Paso 2.',
    thirdTitle: 'OPTIMIZACIÓN CONTINUA',
    thirdDescription: 'MONITORIZAMOS Y MEJORAMOS LOS RESULTADOS CONSTANTEMENTE',
    thirdStep: 'Paso 3.',
  },
  en: {
    title: 'From Idea to Action',
    description: 'in 3 simple steps',
    subtitle: 'Your customers want fast, clear, and instant answers.',
    subtitleBold: 'With OrishIA, that becomes your competitive advantage.',
    firstTitle: 'ANALYSIS & DIAGNOSIS',
    firstDescription: 'WE IDENTIFY YOUR SPECIFIC NEEDS',
    firstStep: 'Step 1.',
    secondTitle: 'CUSTOM SETUP',
    secondDescription: 'WE DESIGN A TAILOR-MADE SOLUTION',
    secondStep: 'Step 2.',
    thirdTitle: 'CONTINUOUS OPTIMIZATION',
    thirdDescription: 'WE CONSTANTLY MONITOR AND IMPROVE RESULTS',
    thirdStep: 'Step 3.',
  },
};